#!/bin/bash

usage() {
cat << EOF
Usage: 
  co [-b][-] [PARTIAL_BRANCH_NAME]
    PARTIAL_BRANCH_NAME ...... A partial or full name of the branch
    -b ..... Create a new branch
    -  ..... Move to the most recent branch checked out
EOF
}

operator=
key=$1

case $key in
  -b)
  operator=$key
  branch_name=$2
  ;;
  -)
  branch_name="$(git reflog | grep checkout | awk 'NR==1 {print $6}')"
  ;;
  *)
  branch_name="$(git branch | grep $key)"
  ;;
esac

git checkout $operator $branch_name

