#!/bin/bash

usage() {
cat << EOF
Usage: 
  klog POD_NAME -n NAMESPACE
    POD_NAME ...... A partial name of the pod to get logs from
    NAMESPACE ........ The kubernetes namespace where the pod is running
EOF
}


POSITIONAL=()

while [[ $# -gt 0 ]]
do
  key="$1"
  case $key in
      -n|--namespace)
      namespace="$2"
      shift # past argument
      shift # past value
      ;;
      -h|--help)
      usage && exit 1;
      ;;
      *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL[@]}"
pod_name=$1

if [ -z "$namespace" ]; then
  namespace='default'
fi


pod=$(kpo $pod_name -n $namespace)

kubectl logs $pod -n $namespace $@
